application: image-test
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /img
  static_dir: static/img
- url: /fancy
  static_dir: static/fancy
- url: /css
  static_dir: static/css
- url: /redactor
  static_dir: static/redactor

- url: /.*
  script: image-test.app